services:
    
  frontend-serve:
    image: nginx:latest
    container_name: edirom-online-frontend-serve
    volumes:
      - ${FRONTEND_PATH}:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 127.0.0.1:8089:80

  frontend-build:
    image: ghcr.io/bwbohl/sencha-cmd:2.1.0
    container_name: edirom-online-frontend-build
    volumes:
      - ${FRONTEND_PATH}:/app
    command: ["./build.sh testing && tail -f /dev/null"]

  backend:
    build:
      context: ./backend   
      dockerfile: Dockerfile
      args:
        REPO: ${BE_REPO:-https://github.com/Edirom/Edirom-Online-Backend.git}
        BRANCH: ${BE_BRANCH:-develop}
        EDITION: ${EDITION_XAR}
      ports:
        - 8080:8080
