services:
    
  frontend-serve:
    build:
      context: ${FRONTEND_PATH}
      dockerfile: docker/Dockerfile
    container_name: edirom-online-frontend-serve
    volumes:
      - ${FRONTEND_PATH}:/usr/share/nginx/html
    environment:
      - APP_PATH=/build
    ports:
      - 127.0.0.1:8089:80

  frontend-build:
    image: ghcr.io/bwbohl/sencha-cmd:latest
    container_name: edirom-online-frontend-build
    stdin_open: true
    tty: true
    volumes:
      - ${FRONTEND_PATH}:/app
    working_dir: /app


  backend: 
    build:
      context: ${BACKEND_PATH}
      dockerfile: Dockerfile
    container_name: edirom-online-backend
    volumes:
      - ${BACKEND_PATH}:/app
    environment:
      - EXIST_PASSWORD=korngold
    ports:
      - 127.0.0.1:8080:8080
