server {
    listen       80;
    server_name  localhost;

    location / {
        root   /usr/share/nginx/html/build;
        index  index.html index.htm;
    }

    location ~ ^/images/(https?://.+)$ {
        resolver 8.8.8.8;
        proxy_pass $1;
        proxy_set_header Host $proxy_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_ssl_server_name on;
        
        # CORS headers
        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS' always;
    }
}
